language: php

php:
    - "5.3"

before_script:
    - mysql -e 'drop database if exists `anazutest`; create database `anazutest`;'
    - composer install -v --dev

script:
    - mkdir -p build/logs 
    - phpunit --colors --bootstrap unittests/bootstrap.php --configuration phpunit-travis.xml --coverage-clover build/logs/clover.xml unittests

after_script:
    - php vendor/bin/coveralls -v