<?php

namespace Anazu\Index;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-05 at 19:13:09.
 */
class IndexerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Indexer
     */
    protected $indexer;
    
    /**
     *
     * @var Data\Interfaces\IDataDriver
     */
    protected $mockDriver;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mockDriver = $this->getMock('\Anazu\Index\Data\Interfaces\IDataDriver');
        $this->indexer = new Indexer($this->mockDriver);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Anazu\Index\Indexer::setTokenizer
     * @covers Anazu\Index\Indexer::getTokenizer
     * @todo   Implement testSetTokenizer().
     */
    public function testGetSetTokenizer()
    {        
        $old_token = $this->indexer->getTokenizer();        
        $this->assertNull($old_token);
        
        $tokenizer = $this->getMock('\Anazu\Analysis\Tokenizer');
        $this->indexer->setTokenizer($tokenizer);
        
        $new_token = $this->indexer->getTokenizer();
        $this->assertSame($tokenizer, $new_token);
    }

    /**
     * @covers Anazu\Index\Indexer::queueDocument
     * @todo   Implement testQueueDocument().
     */
    public function testQueueDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anazu\Index\Indexer::dequeueDocument
     * @todo   Implement testDequeueDocument().
     */
    public function testDequeueDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anazu\Index\Indexer::removeDocument
     * @todo   Implement testRemoveDocument().
     */
    public function testRemoveDocument()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Anazu\Index\Indexer::commitInterfaces
     * @todo   Implement testCommit().
     */
    public function testCommit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
