<?php

namespace Anazu\Index\Data\Abstracts;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-06 at 16:40:01.
 */
class AbstractColumnTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractColumn
     */
    protected $column;

    /**
     *
     * @var string
     */
    protected $name;

    /**
     *
     * @var \Anazu\Index\Data\Interfaces\IValueType
     */
    protected $type;

    /**
     *
     * @var string
     */
    protected $index;

    /**
     *
     * @var int
     */
    protected $default;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->name = 'column';
        $this->type = $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractValueType', array('varchar', 10));
        $this->index = 'index';
        $this->default = 25;
        $this->column = $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array($this->name, $this->type, $this->default, $this->index));
    }

    public function testGetName()
    {
        $this->assertEquals($this->name, $this->column->getName());
    }

    public function testGetType()
    {
        $this->assertSame($this->type, $this->column->getType());
    }

    public function testGetIndex()
    {
        $this->assertEquals($this->index, $this->column->getIndex());
    }

    public function testGetDefaultValue()
    {
        $this->assertEquals($this->default, $this->column->getDefaultValue());
    }
    
    public function testGetNullIndex()
    {
        $column = $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array($this->name, $this->type));
        $this->assertNull($column->getIndex());
    }

    public function testGetNullDefaultValue()
    {
        $column = $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array($this->name, $this->type));
        $this->assertNull($column->getDefaultValue());
    }

    /**
     * @expectedException \InvalidArgumentException
     */
    public function testConstructInvalidNameObjectGiven()
    {
        $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array($this->column, // <- oops
                    $this->type, $this->default, $this->index));
    }
    
    /**
     * @expectedException \InvalidArgumentException
     */
    public function testConstructInvalidNameIntGiven()
    {
        $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array(60, // <- oops
                    $this->type, $this->default, $this->index));
    }
    
    /**
     * @expectedException \InvalidArgumentException
     */
    public function testConstructInvalidIndexObjectGiven()
    {
        $this->getMockForAbstractClass('\Anazu\Index\Data\Abstracts\AbstractColumn'
                , array($this->name, $this->type, $this->default, 
                    $this->column // <- oops
                    ));
    }
}
